apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCVnF7Fw5z9VNNoaQhSi25cyDKOEJdjgcF94zYw2BAS53AgqVrWTq8dQFxYls4Ztp0w5tNwzTSExtIn6jdFS6NojdSp+WILo8A1HCHaJaO6sxIuheW/VYtTKFZzK6hoja7UYMcZTD/O8OvVbvyOsF2ZE+WAo7q+G/hxanQCvVKrhGUSbh+VKjbfxlfnSegA6j95N6gAmnJY6cyIGe5nrDLoPiWxUS00W2HyxwfEup934Q8/dyntsShmgGe7C3D1DqKsi+AI8XrjYNXsXb1ViZfIrPmRWlMwrCzvD/O16qjW/9Qjr/LI6++MxbYuY/R10kbq2phcsrQbfuWZb2W6Azs763eYAUnyDQrEO80iIyUYW6kYwPXgpIRu4TjiooyANBEHB0QXktrXwBFkPYeJ8G31/q/5TrsZTjxHdVEyLU4BkfQcMcaFPeQmjw+mszMhYezBLBKv1X8gJsIay3IKe3EmMkxhra1Fx3MQFRro/Yscr9YJsTt8fpXS6BUErnT6hci8Yp3y0nDNIehn2rghtJ9f8ClaELGkHDmFL2qKLIlQEnCbUt8P9po7hzPnGIu4V+ylYm1RxtPG+uBn9JsoBoipRrTlfkNMopI6grkvCL9Ofsf/t2c4WMHySvBvD2pUsgfoL8wlVM+OxLQ3+8+CSjQb9t21lj06ub6jw+Dwq5beKoWQr1uNlHr2zJCcKGGv1PDpg//55xsNP82WgutXNDAzTlGbteXFQz0Dzei6zvJP+Nz5mVhPKBAuaoDsvF+Ud5lZNhY9bBAV73nqHfs0cTznmfnYjPgVeyYeeMaXdHmWp2D7NdI+h2Yd0uSzgobDH+FridDv6U1d0i5T6i3nwMQFo50Zn5BNMq37bI+TDeuWrM8rvvipuKDnbgFhb0O0xbALPMdRS46VsfJMV6eCp7/cupPCRoHwPRjohSk+7gWJuUeQOo+5xPSM9bMzkZ+FEDepEH7P+XaicSrpJqE8OLgIV6H/ZDXt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

