apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAYyl2Ul4l9xS9mzs30/j+BKGmpl/hXjcFWr3dpH1CGOLyz+KNipMSNx/8mYAixbmMX6PKC2ItNSbLWe7SgLXKGSem8df39y8hmc0qvWkgLUNQrIgu2Z6ufcbPYsOHUDYzVFnaQ6EGxWASKo2Bd9fG8m7+3KsZey/vYOwX+LM9KmpBGEAgLEesAp2elKfG1xTc8y5jFNHjHI8dOoZqISCHb0cUPx6fDvT0DOuxNrKMiwRgEC2WJVwZoL2QMWcYXZNqC+cg5vmOCWZtZRNGBFgwmDj6ZtFpivT2IrB+cUv6H+umtdwo6AIBCKinNcriwAf1Ow3nfVChTTwvb5nG+FcsfFalHV/l+g4a+EknzjQtMNrHQEKiSstAjWMUBQ1T7ej2fQVtM1W6LSb+ZHzYoyXgvunOeyBtrG5ucsmgxu0aDYAFxd+FQp0rK4ugVaFfIXqkUa9NWjZAz/71MXCCuWoUt/PNT8hvHUygtF2k5R4WeVffSKOP5EHvt2oxtq52gd5UZeK1jYeBZitLNp8HLZk1ptCKoZTjGN7v7pKT8nQ20ttqPj+jwJN60SHiNf/bdX3ziKuZNmJOiYERJegAlby0Zn7NW4SpZe1XXIjzcKBjMwb5qJoR6K9K2JVSThQQzrwx9F+Xzup33fSbwpJPHkqYTi5Gu2nYybhFha1Ho8NfNNRUQ9DWPdUGg6h5kv7lFcJZvTQJx5qx0+KMH9G7qwJYxxl6r+ak3QcBuQKKR2KwI8uDPQEmO35TP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

